package de.itwerkstatt.radiopi.entities;

public record RadioStation(String id, String name, String imagePath) {
    /**
     * Generates a unique identifier for the radio station based on its name.
     * The ID is generated by converting the name to lowercase and replacing
     * non-alphanumeric characters with hyphens.
     *
     * @param name The name of the radio station.
     * @return A unique identifier string for the radio station.
     */
    public static String generateIdFromName(String name) {
        return name.toLowerCase().replaceAll("[^a-z0-9]", "-");
    }

    public RadioStation(String name, String imagePath) {
        this(RadioStation.generateIdFromName(name), name, imagePath);
    }
}
